### ISSUE TITLE
Compilation error from opentype

### ISSUE THREAD

**Issue by Gowthamkosaraju** [opentypejs/opentype.js#667]
## Current Behavior
While building the app for dev environment  getting an error from opentype

`err: npm ERR! string.prototype.codepointat not accessible from opentype.js`. When i checked [package](https://github.com/sindresorhus/code-point-at) it's deprecated

<img width="659" alt="Screenshot 2024-01-02 at 1 38 50 PM" src="https://github.com/opentypejs/opentype.js/assets/5729762/b7c664e1-0a4b-4b98-89b6-4f365605a410">

Currently i am using version 1.3.4
<img width="897" alt="Screenshot 2024-01-02 at 1 36 57 PM" src="https://github.com/opentypejs/opentype.js/assets/5729762/9550a822-d492-40c8-9c34-4251c50f0b24">

Any solution to this problem?

## Your Environment

* Version used: 1.3.4
* Browser Name and version: chrome
* Node version: v14.21.3
* Webpack version: 5.88.2

**Comment by ILOVEPIE** [comment]
Version 1.3.4 is heavily outdated, we're working on version 2.0.0, but we are waiting on a few blocking PRs before we can release it. We may do a prerelease version while waiting for those PRs.
